pipeline {
  agent {
    label 'docker-agent'
  }
  stages {
    stage('Build image') {
      steps {
        dir('compile') {
          sh 'docker build -t jdbalgos/portfolio:latest -t jdbalgos/portfolio:$(date +%s) --build-arg CACHEBUST=$(date +%s) .'
          }
        }
      }
    stage('Push') {
      steps {
        sh 'docker image push --all-tags jdbalgos/portfolio:latest'
      }
    }
  }
}
